name: index-tts
channels:
  - conda-forge
  - defaults

dependencies:
  - python=3.10
  - ffmpeg
  - pytorch>=2.1.2,<3.0
  - torchaudio>=2.2.0
  - pynini==2.1.6

  - pip
  - pip:
    - sentencepiece>=0.1.97
    - transformers>=4.36.2
    - accelerate>=0.25.0
    - tokenizers>=0.13.3,<0.16.0
    - omegaconf>=2.3.0
    - einops==0.8.1
    - numpy>=1.23.0
    - librosa>=0.10.0
    - WeTextProcessing>=1.0.0
    - git+https://github.com/index-tts/index-tts.git@main#egg=indextts

