[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "tts_playground"
version = "0.0.1"
description = "Unified TTS Playground with multiple open-source adapters"
authors = [{ name = "Nicolas PREVOT", email = "nicolasprevot57@gmail.com" }]
requires-python = ">=3.12,<3.13"
readme = "README.md"
dependencies = [
    "soundfile>=0.13.1",
]

[project.optional-dependencies]
f5 = [
    "torch",
    "torchaudio",
    "f5-tts>=1.1.7",
    "bigvgan>=2.4.1",
]
kokoro = [
    "kokoro>=0.9.4",
    "misaki[en]>=0.9.4",
    "torch",
    "torchaudio",
]
fishaudio = [
    "fish-speech",
    "torch",
    "torchaudio",
]
kyutai = [
    "moshi>=0.2.6,<0.3",
    "torch>=2.2.0,<2.8",
    "torchaudio",
]
chatterbox = [
    "chatterbox-tts>=0.1.2",
]
dia = [
    "resampy>=0.4.3",
    "transformers",
    "torch",
]

[tool.uv.sources]
torch = [
    { index = "pytorch-nightly", extra = "f5" },
    { index = "pytorch-nightly", extra = "kokoro" },
    { index = "pytorch-nightly", extra = "fishaudio" },
    { index = "pytorch-cu128", extra = "kyutai" },
    { index = "pytorch-cu128", extra = "dia" },
]
torchaudio = [
    { index = "pytorch-nightly", extra = "f5" },
    { index = "pytorch-nightly", extra = "kokoro" },
    { index = "pytorch-nightly", extra = "fishaudio" },
    { index = "pytorch-cu128", extra = "kyutai" },
]
fish-speech = { git = "https://github.com/fishaudio/fish-speech.git" }
transformers = { git = "https://github.com/huggingface/transformers.git"}
indextts = { git = "https://github.com/index-tts/index-tts.git"}

[[tool.uv.index]]
name = "pytorch-nightly"
url = "https://download.pytorch.org/whl/nightly/cu128"

[[tool.uv.index]]
name = "pytorch-cu128"
url = "https://download.pytorch.org/whl/cu128"

[[tool.uv.index]]
name = "pypi"
url  = "https://pypi.org/simple"

[tool.uv]
package = true
prerelease = "allow"
index-strategy = "unsafe-best-match"
conflicts = [
    [
      { extra = "kyutai" },
      { extra = "kokoro" },
      { extra = "f5" },
      { extra = "fishaudio" },
      { extra = "chatterbox" },
      { extra = "dia" },
    ],
]
