[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "tts_playground"
version = "0.0.1"
description = "Orchestrator for TTS Playground"
authors = [{ name = "Nicolas PREVOT", email = "nicolasprevot57@gmail.com" }]
requires-python = ">=3.12"
readme = "README.md"
dependencies = [
    "soundfile>=0.13.1",
    "loguru",
    "pydantic>=2.9.2",
    "fastapi>=0.116.1",
    "uvicorn[standard]>=0.35.0",
    "python-multipart>=0.0.20",
    "httpx>=0.28.1",
    "celery",
    "redis",
    "tts-core",
]

[tool.uv.workspace]
members = [
    "libs/*",
]

[tool.uv.sources]
tts-core = { workspace = true }

[tool.hatch.build.targets.wheel]
packages = ["src/tts_playground"]