vocab_file: ""
save_chunk: !!bool false
remove_silence: false

hf_cache_dir: "D:/.hf_cache"

vocoder_name: vocos  # vocos or bigvgan
vocoder_is_local: false
vocoder_local_path: ""

model: "F5-TTS"
model_cfg:  # loaded after if empty
ckpt_file: ""

gen_text: "Here we generate something just for test."
gen_file: ""
gen_json: 

output_dir: "tests"
output_file: "infer_result.wav"

user_target_rms: 0.1
user_cross_fade_duration: 0.15
user_nfe_step: 32
user_cfg_strength: 2.0
user_sway_sampling_coef: -1.0
user_speed: 1.0
user_fix_duration: 


voices:
  main:
    ref_audio: "data/ref/basic_ref_en.wav"
    ref_text: "Some call me nature, others call me mother nature."
    ref_file: ""

# A Town Mouse and a Country Mouse were acquaintances, and the Country Mouse one day invited his friend to come and see him at his home in the fields. The Town Mouse came,
# and they sat down to a dinner of barleycorns and roots, the latter of which had a distinctly earthy flavour. The fare was not much to the taste of the guest, and presently he
# broke out with
# 
# [town] “My poor dear friend, you live here no better than the ants. Now, you should just see how I fare! My larder is a regular horn of plenty. You must come and stay with me,
# and I promise you you shall live on the fat of the land.”
# 
# [main] So when he returned to town he took the Country Mouse with him, and showed him into a larder containing flour and oatmeal and figs and honey and dates.
# The Country Mouse had never seen anything like it, and sat down to enjoy the luxuries his friend provided: but before they had well begun, the door of the larder opened and
# someone came in. The two Mice scampered off and hid themselves in a narrow and exceedingly uncomfortable hole. Presently, when all was quiet, they ventured out again;
# but someone else came in, and off they scuttled again. This was too much for the visitor.
# 
# [country] “Goodbye,”
# 
# [main] said he,
# 
# [country] “I’m off. You live in the lap of luxury, I can see, but you are surrounded by dangers; whereas at home I can enjoy my simple dinner of roots and corn in peace.”
